name: Workflow as a Service

on:
  pull_request:
    branches: [ "dev", "main" ]
  push:
    branches: [ "dev", "main" ]

jobs:
  gitops:
    uses: SeamlessOps/waas/.github/workflows/waas.yml@v1
    with:
      project_type: nx        # Other projects: dotnet (.net), java, node etc
    permissions:
      id-token: write
      contents: read
      actions: read
    secrets: inherit